_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 55
                - 95
                - 105
            "2":
                - 55
                - 95
                - 105
            "3":
                - 2
                - 3
                - 16
                - 23
                - 55
            "4": 3.11.9
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": darwin-arm64
extractor_version:
    value: 0.1.0
pdf_file:
    value: /Users/danny/Desktop/programming/NLP/inovIntell-extractor/Belaroussi 2023.pdf
